### ISSUE TITLE
Suggestion: New leanpub release

### ISSUE THREAD

**Issue by atc0005** [thewhitetulip/web-dev-golang-anti-textbook#102]
With the number of changes that have been merged to master since 2018-06-09, perhaps it's time to cut a new release?

**Comment by thewhitetulip** [comment]
done

**Comment by atc0005** [comment]
Many thanks. Having a fresh copy should help with further proofing.

Thanks also for creating this book in the first place. I'm learning a lot and am staying motivated to continue progressing through the book.

**Comment by thewhitetulip** [comment]
You are very welcome!!
