### ISSUE TITLE
How do you feel about moving code comments from to-the-right to on-top?

### ISSUE THREAD

**Issue by atc0005** [thewhitetulip/web-dev-golang-anti-textbook#103]
@thewhitetulip 

I found several cases while reading the epub version that code comments to the right of the code they were referencing were forcefully wrapped around to the next line, potentially disrupting the flow of the code. How do you feel about moving those to just above the code in question?

I'm attaching a screenshot illustrating how it displays in Google Play Books, though the content looks similar on mobile devices.

![web_apps_in_go_comments_to_the_right_example_2019-07-15](https://user-images.githubusercontent.com/36716992/61266348-105d7900-a759-11e9-8a1e-c0fc9df6d416.png)

Proposed adjustment (or some similar variation):

```golang
 // use `…` to replace the length parameter and Go will
// calculate it for you.
c := [...]int{4, 5, 6}
```

I'm willing to offer a PR with fixes for the ones I highlighted while reading through the book if you're interested.

**Comment by thewhitetulip** [comment]
We can do that.
