### ISSUE TITLE
How do you prefer pull requests to be constructed?

### ISSUE THREAD

**Issue by atc0005** [thewhitetulip/web-dev-golang-anti-textbook#104]
@thewhitetulip 

As an example, if there are header level changes, typos and spacing adjustments, do you want them combined into fewer PRs or more focused on a specific type of change? 

If combined, would you find it helpful to have multiple commits per PR (e.g., one file per commit with all changes to that file) or squashed to one commit containing all changes?

I've got some notes from going through the text (only the first pass at reading as I have much to learn from your book) and would like to begin compiling the changes into acceptable PRs. I figure I would touch base and confirm some details before investing too much work into the effort just yet.

Thanks.

**Comment by thewhitetulip** [comment]
If they are any non technical content change then put all in one PR.

For technical faults, please raise an issue and a PR per issue

**Comment by atc0005** [comment]
> @thewhitetulip: If they are any non technical content change then put all in one PR.
> 
> For technical faults, please raise an issue and a PR per issue

I think I understand. So if I have formatting, typo and other minor changes across several files, include those in one PR. If I have suggestions for code-level changes, those concerns should be raised by way of separate Pull Requests.

**Comment by thewhitetulip** [comment]
Yes, one PR for all non tech changes and another for tech changes
