### ISSUE TITLE
Remove Links section at the bottom of most chapters?

### ISSUE THREAD

**Issue by atc0005** [thewhitetulip/web-dev-golang-anti-textbook#107]
Example from a preview PDF copy:

![antitextbook-footer-links-sections-with-broken-links](https://user-images.githubusercontent.com/36716992/63141010-b2b38b00-bfa9-11e9-83f8-187244254e5a.png)

I'm proposing that we remove these sections if they don't contain any external "See also" style external links (e.g., those intended to provide more information/context).

**Comment by atc0005** [comment]
I get it now. Those links are included at the bottom of the Markdown docs in order to provide a useful navigation link if viewing the content directly from GitHub.

Challenge: Show these links for readers using GitHub, but exclude them from generated documents (PDF, epub, mobi).

**Comment by thewhitetulip** [comment]
Please ignore this. There will be some +- right? We have to merge two formats and there is bound to be some issues.

**Comment by atc0005** [comment]
> Please ignore this. There will be some +- right? We have to merge two formats and there is bound to be some issues.

Acknowledged. 

Per #106 I updated some of the header levels, including the **Links** sections. With the changes there that places the **Links** sections directly into the Table of Contents. That in itself isn't necessarily a bad thing, as any additional "See also" links for further reading would be a great fit for those areas.

The unintentional bit was that the navigation links for web viewing showed up there.

As you indicated, this might be something that can't be easily fixed and might not be worth spending a lot of time on. It would be nice if there was a hook script of some kind that could be triggered when the Markdown files are parsed by Leanpub to remove the references, but again, something for later perhaps.
