### ISSUE TITLE
A package with example code

### ISSUE THREAD

**Issue by gernest** [thewhitetulip/web-dev-golang-anti-textbook#12]
I couldn't find where the examples code is, as I am interested to contribute the code and tests too. So maybe you should add a subdirectory named `examples` so all the examples code can be there.

or if you have it somewhere else please let know.

__PS__: I was about to write a book in my local language( swahili, I'm from tanzania), now I don't think it is necessary. Will instead contribute to this one  so maybe in the future I will just need to translate this.

**Comment by thewhitetulip** [comment]
This is a great idea, the thing is I want to distribute this book as a PDF and my goal is that anyone without an internet connection should be able to use and learn from the book just by reading the PDF document. We can keep a subdirectory and taking the necessary care that we paste the code examples verbatim in the book as well.

So there won't be any dependency, I am from India and here Internet connectivity is terrible, so I want a fully useful PDF file and not just a pointer to a github repo.

**Comment by thewhitetulip** [comment]
@gernest Hey I added a package with example code.

**Comment by thewhitetulip** [comment]
@gernest Hey I added considerable code to the book repo :+1: 
Thanks for the suggestion

**Comment by gernest** [comment]
@thewhitetulip you are welcome, I have a bit tight schedule but when I have time will sure check this out

**Comment by thewhitetulip** [comment]
Not a problem @gernest I am closing this issue for now :smile:
