### ISSUE TITLE
Put gimp image file in repo

### ISSUE THREAD

**Issue by benkasminbullock** [thewhitetulip/web-dev-golang-anti-textbook#13]
For the cover.jpg,

https://github.com/thewhitetulip/web-dev-golang-anti-textbook/blob/master/cover.jpg

would it not be better to put the original Gimp image file in the repo so that people can edit it?

**Comment by thewhitetulip** [comment]
I'll upload it tonight. Meanwhile how did you know I used gimp?

**Comment by thewhitetulip** [comment]
@benkasminbullock Can you comment on that PR?

**Comment by benkasminbullock** [comment]
> perl -MImage::Info -e "print Image::Info::image_info('cover.jpg')->{Comment}"

> Created with GIMP

**Comment by thewhitetulip** [comment]
Cool. Got to try Perl 6!
