### ISSUE TITLE
Overall Editorial Theme

### ISSUE THREAD

**Issue by thewhitetulip** [thewhitetulip/web-dev-golang-anti-textbook#14]
Hi @brudgers  I missed out on your comment on my HN post, and now there is no way to contact you. The editorial theme I have mentioned in the readme document here, is there more information required on that?

What prompted writing this book:

While learning web dev with Go it was very difficult to understand real life examples, most of all the tutorials/books I read gave some ridiculously simple examples and then somehow expect the total newbie to understand all the complicated logic that goes with an actual real life webapp.

Also PRs are welcome!

**Comment by thewhitetulip** [comment]
Updated wiki pages, https://github.com/thewhitetulip/web-dev-golang-anti-textbook/wiki/

**Comment by thewhitetulip** [comment]
@brudgers Updated [wiki pages](https://github.com/thewhitetulip/web-dev-golang-anti-textbook/wiki/)

**Comment by brudgers** [comment]
Sorry I missed your notification. I don't use Github very often currently. I tend to use bitbucket because of the free private repositories (which meets a couple of my typical use cases: academic class work and confidential projects). However, there is an email in my Hacker News profile. I would be happy to chat. Ben

**Comment by thewhitetulip** [comment]
I didn't find an email in your HN profile!

**Comment by brudgers** [comment]
It's not in there directly...it's the 'now with gmail'. Sorry about the confusion. Ben

**Comment by thewhitetulip** [comment]
I emailed your username at gmail.com. I hope it is the correct email!

**Comment by brudgers** [comment]
It's my full name.

**Comment by thewhitetulip** [comment]
Okay :+1:

**Comment by thewhitetulip** [comment]
I emailed you yesterday.
