### ISSUE TITLE
Images broken in PDF version

### ISSUE THREAD

**Issue by astropanic** [thewhitetulip/web-dev-golang-anti-textbook#17]
Hi,

The images in the PDF are broken, for example https://raw.githubusercontent.com/thewhitetulip/web-dev-golang-anti-textbook/master/content/images/2.2.basic.png is missing on page 21

**Comment by thewhitetulip** [comment]
The thing is, the images are taken from the wonderful book by astaxie, and even in his version of the book, the images are missing. Will have to investigate it further, there would be some gotcha on gitbook

**Comment by thewhitetulip** [comment]
I am migrating the book from gitbooks to leanpub. Images are being rendered in the preview version.

**Comment by thewhitetulip** [comment]
@astropanic I think gitbook images would have been fixed now. If you want I'll email you the preview copy of the PDF.
