### ISSUE TITLE
Images wich drawing programm?

### ISSUE THREAD

**Issue by norbertfuhs** [thewhitetulip/web-dev-golang-anti-textbook#26]
Hi Suraj!

With which drawing program did you make your graphs?

**Comment by thewhitetulip** [comment]
I am sorry to diaappoint you man, the Why Go chapter is adapted from an open source book by @astaxie. 
I tried drawing image in GIMP, but my image skills suck big time :D

How well do you like the book? I'd love some feedback!

**Comment by norbertfuhs** [comment]
The book is great but I think we should redraw this stuff with common tools like Google draw and simplify them. I 'll update some stuff on Installation and Graphs and will post an PR later!

**Comment by thewhitetulip** [comment]
Wow, I didn't know there is something called Google Draw, plus I never paid attention on the images till now. My main motto was to build an awesome introductory book, God knows how I learned all this on my own! So I wanted to write the book which I wish I had when I started learning Go. :-)

That being said, yes it'll be better to redraw images customizing them. But then again, a chapter on socket programming and unit testing is pending, a lot of refactoring is pending! I'll post the pending items in the wiki page.

I use the to do manager I wrote about in the book to track the dev work, so github and that is a bit disconnected.

**Comment by norbertfuhs** [comment]
Okay jsut let me know whats pending and i will see if I can help I know websockets from Javascript / node.js and of course from [build-web-application-with-golang](https://astaxie.gitbooks.io/build-web-application-with-golang/content/en/08.2.html)

Maybe I can help

**Comment by thewhitetulip** [comment]
A chapter on websockets would be awesome!

**Comment by thewhitetulip** [comment]
https://github.com/thewhitetulip/web-dev-golang-anti-textbook/issues/27 let's move discussion of websockets here
