### ISSUE TITLE
error undefined: message in chapter 2.1

### ISSUE THREAD

**Issue by adrinux** [thewhitetulip/web-dev-golang-anti-textbook#29]
Using go 1.7 on osx and working through 2.1WebAppDesign.md I get errors when running go build and build failure.
```
± go build
# github.com/adrinux/Tasks
./main.go:41: undefined: message
./main.go:50: undefined: message
./main.go:59: undefined: message
./main.go:68: undefined: message
./main.go:77: undefined: message
./main.go:86: undefined: message
./main.go:95: undefined: message
./main.go:104: undefined: message
./main.go:113: undefined: message
./main.go:122: undefined: message
./main.go:122: too many errors
```

It seems message is out of scope when calling write. Declaring it first and only assigning within if works ok:

```
func ShowAllTasksFunc(w http.ResponseWriter, r *http.Request) {
	var message string
	if r.Method == "GET" {
		message = "all pending tasks GET"
	} else {
		message = "all pending tasks POST"
	}
	w.Write([]byte(message))
}
```

**Comment by thewhitetulip** [comment]
True that, I will fix this issue. I just want one feedback from you, as a reader,  do you think it'd  be better if the book provided actual code examples adding upto the full app at the end?

**Comment by appleboy** [comment]
@thewhitetulip it would be better to store all full example code in new folder for every section.

**Comment by thewhitetulip** [comment]
@appleboy The thing is, the book is based out of https://github.com/thewhitetulip/Tasks

So from the chapter 3 and beyond they can directly check Tasks application's source code.

So I am in a dilemma regarding if there is a point in adding source codes in both the places. Also Tasks will be updated more often than the book, so the latest code is always going to be there in Tasks.
