### ISSUE TITLE
Images are broken on pdf

### ISSUE THREAD

**Issue by hebeka** [thewhitetulip/web-dev-golang-anti-textbook#31]
The PDF at README.md link doesn't show images. Online one is ok though.

**Comment by thewhitetulip** [comment]
yes, that is.because gitbooks has some error I can't  fix! I am migrating the book to leanpub, leanpub is able to generate the pdf fine. drop me an email at sapatil@live.com, I will email you the PDF.

I haven't  finished the total PDF yet, still a preview version

**Comment by thewhitetulip** [comment]
@hebeka https://github.com/thewhitetulip/web-dev-golang-anti-textbook/commit/26091335106be1edf41851cf3e39a39541e98f25
