### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by rongyi** [thewhitetulip/web-dev-golang-anti-textbook#35]
In chapter: 2.0implementationBasics.md,

> We take a sub string of the URL and remove the /delete/ part and we have the ID of the task.

but the code above we strip the /tasks/ actually, is this a typo?

**Comment by tedyoung** [comment]
You're right, it should say

> remove the `/tasks/` part

File a Pull Request?

**Comment by thewhitetulip** [comment]
Yes, it is a typo. It is embarassing. If you want to file a PR I'd be happy to merge it :-)

**Comment by rongyi** [comment]
it's a tiny modification :), you just change it.

**Comment by thewhitetulip** [comment]
okay :-)
