### ISSUE TITLE
"sqlite3" advice is for Linux only

### ISSUE THREAD

**Issue by benkasminbullock** [thewhitetulip/web-dev-golang-anti-textbook#4]
On this page

https://github.com/thewhitetulip/web-dev-golang-anti-textbook/blob/master/content/2.2database.md

This advice:

> In case you don't know how to install software in your *nix machine, type sqlite3 in your terminal, your package manager will show how to download it for ubuntu type sudo apt-get install sqlite3

is valid for Linux only.

**Comment by thewhitetulip** [comment]
Okay, I have never worked/owned a Mac and I have never worked on Windows. Could you please tell me what are the respective names of sqlite on those platforms?

**Comment by benkasminbullock** [comment]
I use FreeBSD and the command to install it is "pkg install sqlite3".

**Comment by thewhitetulip** [comment]
I have updated the description and left the installation part out of the text.
