### ISSUE TITLE
Type in intro to Go.

### ISSUE THREAD

**Issue by voldemortensen** [thewhitetulip/web-dev-golang-anti-textbook#55]
In the godoc section, there is the following sentence:

> “The packages **_were_** comments aren’t present show up as blank pages in godoc.”

This should be:

> “The packages **_where_** comments aren’t present show up as blank pages in godoc.”

**Comment by thewhitetulip** [comment]
I think you have already sent a PR so I am closing this issue.

**Comment by voldemortensen** [comment]
Yep, most repos I've worked with prefer opening an issue and then a pull request (I forgot to reference the issue in the pull request). Thanks for the great book!

**Comment by thewhitetulip** [comment]
It's my pleasure that this book is helpful :-)

I don't follow much standards as far as governance is concerned
