### ISSUE TITLE
Why not use ParseGlob in the templates example?

### ISSUE THREAD

**Issue by benkasminbullock** [thewhitetulip/web-dev-golang-anti-textbook#9]
Seems like this code in the templates example is just reproducing the [ParseGlob](https://golang.org/pkg/text/template/#ParseGlob) method:

<pre>
Reading template:

		templates, err = template.ParseFiles(allFiles...)
		
Where allFiles is populated as below:

		var allFiles []string
		templatesDir := "./public/templates/"
		files, err := ioutil.ReadDir(templatesDir)
		if err != nil {
			fmt.Println("Error reading template dir")
		}
		for _, file := range files {
			filename := file.Name()
			if strings.HasSuffix(filename, ".html") {
				allFiles = append(allFiles, templatesDir+filename)
			}
		}
		</pre>

For example, in my program this is the exact code:

    var tmplDir = "/home/ben/projects/bagapp2/tmpl/"

    var templates = template.Must(template.ParseGlob(tmplDir + "*.html"))

**Comment by thewhitetulip** [comment]
Yes, it does make sense.

**Comment by thewhitetulip** [comment]
You know, we can use the `ParseGlob` function, but I feel that we should use the ParseFiles just for the sake of showing how do we implement that functionality manually. Of course we can use the much better function but it would be of merit to have our implementation of as many functions as possible to teach our readers about Go, we can mention ParseGlob, I'll do that now.

**Comment by benkasminbullock** [comment]
It sounds like a good idea to have methods of teaching in the book.

Do you have any kind of design documents or roadmap documents? I think it would help collaborators if you wrote down the "philosophy" of the book somewhere.

**Comment by thewhitetulip** [comment]
As of now there is no mention of philosophy, I'll write it in the wiki section of github tonight

**Comment by benkasminbullock** [comment]
For example, if someone is thinking of adding a section to the document they might not feel comfortable  adding it in case it doesn't accord with your planned design for the book. At the moment it is not completely finished, so it would be a help for contributors to have an idea what you are planning to do. Perhaps if you just edited your responses on Reddit and Golang-nuts into a document, that would be enough to guide people. I personally found it interesting because I'm currently developing something using SQLite and Go with templates.

**Comment by thewhitetulip** [comment]
:+1:

**Comment by thewhitetulip** [comment]
Does [this] (https://github.com/thewhitetulip/web-dev-golang-anti-textbook#philosophy) explain the philosophy? Or do I need to add something more @benkasminbullock
