### ISSUE TITLE
How do you generate new ebooks from content in this repo?

### ISSUE THREAD

**Issue by atc0005** [thewhitetulip/web-dev-golang-anti-textbook#97]
First of all, many thanks for providing both the book and the source files used to produce the book. I'm a newbie to Go and have found the book very helpful as a companion to some other books I'm working through, though it is without a doubt very useful all on its own.

As I work through the material, I've found some minor issues, several of which have been reported and fixed by Pull Requests submitted by others (e.g., #92). I've got some others that I wish to submit, but I'd like to test the changes by generating fresh ebooks for comparison, either before submitting PRs or just after to proof the work.

I suspect that perhaps you're using `pandoc`, but wanted to touch base and confirm before I went in that direction.

Thanks in advance for your help.

**Comment by thewhitetulip** [comment]
I am not using pandoc, I am using markdown. I further use leanpub to generate the PDF. But you don't have to worry about it. If your markdown is valid, as in, github is able to render it correctly then you should submit the PR. I'll make the changes if there are some issues.

Perfection is a journey and not a destination! Feel free to submit a PR.

**Comment by atc0005** [comment]
> I am not using pandoc, I am using markdown

Thanks for the feedback. I mistakenly assumed that you might have been using the `pandoc` tool to convert markdown into other formats, but you've already corrected that assumption when you noted that you use leanpub. 

I checked and I see that free users can regenerate/publish books up to 10 times a month, so presumably that makes it possible to generate a test copy of this book from a fork of the upstream repo for proofing purposes. While not as flexible as building via a local environment, it at least means the results should be reproducible.

I briefly attempted to compile a fresh epub using pandoc, but didn't get far enough into the process to work out the kinks. If/when I try again and have success I'll try to come back and update this issue with applicable details.

**Comment by atc0005** [comment]
Follow-up:

While I've not tested further with pandoc, I did find that it's relatively easy to setup a leanpub account, create a new unpublished book and point it at a fork of this repo. This allows for either on-demand preview builds (epub, PDF, mobi) or automatic builds based on GitHub webhook support when pushing changes to the associated GitHub repo (fork).

Thus far it's working well enough for proofing work prior to submitting a Pull Request.

**Comment by thewhitetulip** [comment]
As long as Github markdown rendering is working, you should not worry man. The final responsibility is with me, not you. I'll take care of it.
