### ISSUE TITLE
Multiple headers not rendering properly

### ISSUE THREAD

**Issue by atc0005** [thewhitetulip/web-dev-golang-anti-textbook#98]
I noticed that while reading the epub version the level 2 header for Constants was rendered as `## Constants`, literally within the text instead of a formatted header as intended. I double-checked and the `2018-06-09` version available from leanup has the same issue in the PDF format also.

Attaching a screenshot for illustration.
![constants_header_not_rendering_properly_2019-06-16](https://user-images.githubusercontent.com/36716992/59577158-31fb1000-9088-11e9-8fb4-2867bcb310eb.png)

I briefly looked over the source Markdown file, but I can't tell for sure if the issue has been addressed since the `2018-06-09` version was released.

**Comment by atc0005** [comment]
I dug further and found that there were several headers similarly affected. Updated this issue title to reflect that.

**Comment by atc0005** [comment]
@thewhitetulip are you interested in Pull Requests to resolve formatting issues, or primarily larger content changes?

**Comment by thewhitetulip** [comment]
All PRs are welcome, it might be small typos fixing or content changes.
